function getInfo() {
	window.numberOfQuestions = 	10;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"FANCY GOLDFISH TRIVIA";
	window.questions = [		"HOW MANY GOLDFISH ARE SOLD EVERY YEAR", 
								"WHAT HAPPENS IF YOU KEEP A GOLDFISH IN THE DARK",
								"HOW LONG HAVE HUMANS BEEN BREEDING GOLDFISH", 
								"DOES A GOLDFISH HAVE ONLY 3-SECONDS OF MEMORY", 
								"WHAT IS ONE THING GOLDFISH CAN’T DO, THAT HUMANS CAN",
								"DO GOLDFISH HAVE STOMACHS",
								"CAN GOLDFISH SEE MORE COLORS THAN HUMANS",
								"HOW OLD IS THE OLDEST GOLDFISH ON RECORD",
								"WHAT LARGE THINGS WILL GOLDFISH EAT",
								"HOW MANY DIFFERENT VARIETIES OF GOLDFISH ARE THERE" ];
	window.correctAnswer = [ 	"D", "C", "A", "B", "E", "A", "D", "B", "E", "C" ]; 
	window.answerA = [ 			"2 MILLION", 
								"IT GLOWS", 
								"1,000 YEARS", 
								"AT LEAST 10-SECONDS", 
								"SWIM",
								"NO, THEY USE LONG INTESTINES INSTEAD",
								"NO, GOLDFISH ARE BLIND",
								"LATE TWENTIES",
								"ONLY SMALL DIGESTIBLE BITES",
								"1 MILLION BREEDS"  ];
	window.answerB = [ 			"5 THOUSAND", 
								"IT DISAPPEARS", 
								"200 YEARS", 
								"ABSOLUTELY NOT",
								"GET SUNBURNED",
								"YES, IT’S HUGE",
								"YES, A TRILLION COLORS",
								"MID FORTIES",
								"THINGS BIGGER THAN THIER OWN HEADS",
								"40 BREEDS" ];
	window.answerC = [ 			"9 TRILLION",
								"IT TURNS TOTALLY WHITE",
								"1,000,000 YEARS", 
								"MAYBE", 
								"FLOAT", 
								"THEY DON’T DIGEST THIER FOOD AT ALL",
								"GOLDFISH CAN ONLY SEE IN BLACK AND WHITE",
								"A HUNDRED",
								"THEY DON’T EAT",
								"200 BREEDS" ];
	window.answerD = [ 			"480 MILLION",  
								"IT TURNS INTO A CAT",
								"4 YEARS", 
								"YES, THEY ARE STUPID",
								"DRINK WATER",
								"THEY USE A GRINDER INSTEAD",
								"YES, THEY SEE ONE MORE COLOR THAN HUMANS",
								"MID TEENS",
								"THEY EAT THROUGH A STRAW",
								"6 THOUSAND BREEDS" ];
	window.answerE = [ 			"3 HUNDRED", 
								"IT STAYS THE SAME", 
								"500 YEARS", 
								"WHO KNOWS", 
								"CLOSE THEIR EYE", 
								"FOOD, WHO NEEDS FOOD",
								"NO, GOLDFISH DON’T SEE COLORS UNDERWATER",
								"FIVE YEARS OLD",
								"WHATEVER FITS IN THIER MOUTHS",
								"5 BREEDS" ];

								
	window.response = [ 		"OVER 480 MILLION FANCY GOLDFISH ARE SOLD EVERY YEAR", 
								"IF YOU KEEP A GOLDFISH IN THE DARK, IT TURNS TOTALLY WHITE, BECAUSE LIGHT HELPS THEM PRODUCE PIGMENT IN THEIR SKIN", 
								"FANCY GOLDFISH HAVE BEEN BRED BY HUMANS FOR OVER 1,000 YEARS", 
								"THE 3-SECOND MEMORY THING IS A TOTAL MYTH, GOLDFISH HAVE EVEN BEEN TRAINED TO SOLVE MAZES AND DO TRICKS", 
								"GOLDFISH CAN’T CLOSE THEIR EYES, THEY EVEN SLEEP WITH THEIR EYES WIDE OPEN",
								"GOLDFISH DON’T HAVE STOMACHS, INSTEAD THEY HAVE A LONG INTESTINE THAT DOES THE JOB OF DIGESTING IN DIFFERENT AREAS",
								"GOLDFISH FOUR PRIMARY COLORS, WHICH IS MORE THAN THE THREE THAT HUMANS CAN SEE",
								"THE OLDEST GOLDFISH ON RECORD MADE IT INTO HIS MID FORTIES",
								"THEY EAT ANYTHING THAT WILL FIT IN THIER MOUTHS, INCLUDING THIER OWN BABIES",
								"CURRENTLY, IN 2020, THERE ARE ABOUT 200 BREEDS"  ];














							
}
						